// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen1_Panel1;
extern lv_obj_t * ui_Screen1_Keyboard1;
void ui_event_Screen1_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_Screen1_TextArea1;
void ui_event_Screen1_TextArea3(lv_event_t * e);
extern lv_obj_t * ui_Screen1_TextArea3;
extern lv_obj_t * ui_Screen1_Panel3;
void ui_event_Screen1_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Screen1_Slider2;
extern lv_obj_t * ui_Screen1_Label2;
extern lv_obj_t * ui_Screen1_Switch1;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
