// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_SCREEN1_LABEL1_H
#define _UI_COMP_SCREEN1_LABEL1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Screen1 Label1
#define UI_COMP_SCREEN1_LABEL1_SCREEN1_LABEL1 0
#define _UI_COMP_SCREEN1_LABEL1_NUM 1
lv_obj_t * ui_Screen1_Label1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
